# NumPy
- NumPy bilimsel hesaplamalr yapmak için pratik bir pakettir. büyük ve çok boyutlu diziler ve matrisler için destek sunar.

In [1]:
import numpy as np

## Array oluşturmak

In [2]:
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [3]:
type(a)

list

In [5]:
b = list(range(6, 11))
b

[6, 7, 8, 9, 10]

In [6]:
a + b #liste toplama

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# np.array()

In [9]:
a1D = np.array(a) #list, np.array tipine dönüştürüldü.

In [10]:
print(a1D)

[1 2 3 4 5]


In [11]:
type(a1D)

numpy.ndarray

In [12]:
b1D =np.array(b)

In [13]:
print(b1D)

[ 6  7  8  9 10]


In [14]:
a1D + b1D

array([ 7,  9, 11, 13, 15])

In [15]:
a1D - b1D

array([-5, -5, -5, -5, -5])

In [16]:
a1D * b1D

array([ 6, 14, 24, 36, 50])

In [17]:
a1D / b1D

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
a1D ** b1D

array([      1,     128,    6561,  262144, 9765625])

In [19]:
a, b

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

In [20]:
[a, b]

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [21]:
a2D = np.array([a, b])

In [22]:
print(a2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
a2D * a2D

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

## 1D array oluşturma fonksiyonları

In [26]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [30]:
list(range(5, 10, 2))

[5, 7, 9]

In [31]:
np.arange(5, 10, 2)

array([5, 7, 9])

## np.linspace

In [35]:
#help(np.linspace)

In [36]:
np.linspace(0, 49)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [37]:
np.linspace(5, 50, num=21)

array([ 5.  ,  7.25,  9.5 , 11.75, 14.  , 16.25, 18.5 , 20.75, 23.  ,
       25.25, 27.5 , 29.75, 32.  , 34.25, 36.5 , 38.75, 41.  , 43.25,
       45.5 , 47.75, 50.  ])

## 2D array oluşturma fonksiyonları

### np.eye

In [38]:
np.eye(5) # birim matris

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.eye(6, dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### np.zeros

In [40]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [41]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
np.zeros(shape=(2,3), dtype=int) + 1

array([[1, 1, 1],
       [1, 1, 1]])

## numpy array leri çoğaltma, birleştirme ve değiştirme

In [45]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
b = a

In [47]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
b +=1

In [49]:
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
id(a)

2352597835792

In [51]:
id(b)

2352597835792

In [53]:
c = a.copy()

In [54]:
id(c)

2352618028080

In [55]:
c += 1

In [57]:
print(c)

[ 2  3  4  5  6  7  8  9 10 11]


In [58]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### np.vstack, np. hstack

In [59]:
a = np.array(range(1, 5))
b = np.array(range(5, 9))
c = np.array(range(9, 13))
d = np.array(range(13, 17))

In [60]:
print(a)
print(b)
print(c)
print(d)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [61]:
np.vstack((a, b, c, d))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
np.hstack((a, b, c, d))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## np.diag

In [64]:
np.diag((1, 2, 5, 7, 9))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

In [65]:
np.ones((5, 7), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

### np.block

## rastgele (random9 numpy array'ler oluşturmak

### rand

In [66]:
np.random.rand() 

0.11253097873645357

In [67]:
np.random.rand(5)

array([0.5357029 , 0.20657625, 0.00892041, 0.07430531, 0.7729046 ])

In [68]:
np.random.rand(3, 4)

array([[0.89517568, 0.45443062, 0.00942076, 0.74067386],
       [0.36054787, 0.04367365, 0.04876805, 0.40964725],
       [0.14539838, 0.75578077, 0.27357861, 0.93228446]])

In [69]:
np.random.rand(3, 4) * 10

array([[5.84944323, 4.89562862, 3.19697321, 6.4357816 ],
       [7.94945454, 3.07569954, 9.24818995, 1.15657912],
       [2.79616792, 2.13121782, 9.21105834, 5.58512713]])

In [70]:
big_arr = np.random.randn(10000)

In [71]:
type(big_arr)

numpy.ndarray

In [72]:
len(big_arr)

10000

In [73]:
big_arr.mean()

0.002989994655835939

In [74]:
big_arr.std()

1.0027617752769442

In [75]:
big_arr.max()

3.661445792904397

In [76]:
big_arr.min()

-4.262711790778096

In [77]:
big_arr.argmax()

3006

In [79]:
big_arr[3006]

3.661445792904397

In [80]:
big_arr.argmin()

3367

In [81]:
big_arr[3367]

-4.262711790778096

## seed

In [83]:
np.random.seed(101)
np.random.randn()

2.706849839399938

## arrayleri yeniden şekillendirmek

In [86]:
arr = np.arange(20, 36)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


In [87]:
arr.reshape(4, 4)

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [88]:
arr.shape

(16,)

In [90]:
arr=arr.reshape(4, 4)
print(arr)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


In [91]:
arr.shape

(4, 4)

In [92]:
arr=arr.reshape(2, 8)
print(arr)

[[20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35]]


In [93]:
arr.shape

(2, 8)

In [96]:
arr= arr.reshape(1,16)
print(arr)

[[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]]


In [97]:
arr= arr.reshape(16,1)
print(arr)

[[20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]]


In [98]:
arr.shape

(16, 1)

In [99]:
arr= arr.reshape(2, 2, 2, 2)
print(arr)

[[[[20 21]
   [22 23]]

  [[24 25]
   [26 27]]]


 [[[28 29]
   [30 31]]

  [[32 33]
   [34 35]]]]


In [101]:
arr= arr.reshape(2, 2, 4)
print(arr)

[[[20 21 22 23]
  [24 25 26 27]]

 [[28 29 30 31]
  [32 33 34 35]]]


## indexleme ve dilimleme ( indexing and slicing)

In [106]:
arr = np.arange(0, 35, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


In [108]:
arr[2]

4

In [107]:
arr[6]

12

In [110]:
len(arr)

18

In [113]:
arr = arr.reshape(3, 3, 2)
print(arr)

[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]

 [[24 26]
  [28 30]
  [32 34]]]


In [114]:
arr[1]

array([[12, 14],
       [16, 18],
       [20, 22]])

In [115]:
arr[1][1]

array([16, 18])

In [116]:
arr[1][1][1]

18

In [118]:
arr[0][1][0]

4

## slicing

In [123]:
arr = np.arange(10, 35)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [125]:
arr[3:8]

array([13, 14, 15, 16, 17])

In [127]:
arr[-6:-2]

array([29, 30, 31, 32])

In [128]:
len(arr)

25

In [131]:
arr = arr.reshape(5,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [132]:
arr[1:3]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [133]:
arr[1:3][1:3]

array([[20, 21, 22, 23, 24]])

In [134]:
arr[1:3,1:3]

array([[16, 17],
       [21, 22]])

In [139]:
arr[2: ,3: ]

array([[23, 24],
       [28, 29],
       [33, 34]])

In [145]:
np.random.randint(0, 100, size=50)

array([57, 38, 13, 69, 87, 69, 52,  1, 49,  3, 22, 27, 87, 98, 67,  1, 62,
       35, 23, 51, 95, 93, 84, 20, 26, 52, 16, 46, 99,  9, 53, 94, 47, 84,
       94, 29, 74, 44, 76, 56, 60, 77,  0, 69, 20, 30, 66, 40, 95,  5])

In [148]:
np.random.seed(51)
arr = np.random.randint(0, 100, size=50)
print(arr)

[57 96 73 69 16 21 94 52 37 37 60 94 28 84 36 35 27 28 42 10  6 25 33 77
 39 48 24 40 54 77 28 69 57 18 63 75 67 94 87  7 67 91 61 34 53 30 55 17
 67  8]


In [149]:
bool_arr = arr > 50
print(bool_arr)

[ True  True  True  True False False  True  True False False  True  True
 False  True False False False False False False False False False  True
 False False False False  True  True False  True  True False  True  True
  True  True  True False  True  True  True False  True False  True False
  True False]


In [150]:
arr[bool_arr]

array([57, 96, 73, 69, 94, 52, 60, 94, 84, 77, 54, 77, 69, 57, 63, 75, 67,
       94, 87, 67, 91, 61, 53, 55, 67])

In [151]:
arr[arr > 50]

array([57, 96, 73, 69, 94, 52, 60, 94, 84, 77, 54, 77, 69, 57, 63, 75, 67,
       94, 87, 67, 91, 61, 53, 55, 67])

In [154]:
arr2= np.array([1, 3, 4, 7, 8, 9])
bool_arr2 = np.array([False, False, True, False, True, False])

In [155]:
len(arr2)

6

In [156]:
len(bool_arr2)

6

In [157]:
arr2[bool_arr2]

array([4, 8])

In [160]:
np.random.seed(51)
arr3 = np.random.randint(125, 625, 100)
print(arr3)

[182 610 349 582 322 141 530 347 561 486 546 247 491 162 185 475 153 465
 289 288 536 611 153 551 497 519 131 406 542 586 548 429 149 293 179 330
 497 153 450 182 399 316 200 320 377 475 596 516 378 576 344 314 373 415
 562 283 180 142 320 242 234 261 566 419 266 450 212 194 366 177 254 174
 128 403 280 468 479 576 230 254 443 544 532 560 220 368 602 465 401 407
 433 250 525 299 365 608 244 518 434 347]


In [170]:
arr3[(arr3 > 250) & (arr3 < 400)]

array([349, 322, 347, 289, 288, 293, 330, 399, 316, 320, 377, 378, 344,
       314, 373, 283, 320, 261, 266, 366, 254, 280, 254, 368, 299, 365,
       347])

In [171]:
np.random.seed(51)
arr = np.random.randint(1, 101, size=50)
print(arr)

[58 97 74 70 17 22 95 53 38 38 61 95 29 85 37 36 28 29 43 11  7 26 34 78
 40 49 25 41 55 78 29 70 58 19 64 76 68 95 88  8 68 92 62 35 54 31 56 18
 68  9]


In [172]:
arr[arr > 25]

array([58, 97, 74, 70, 95, 53, 38, 38, 61, 95, 29, 85, 37, 36, 28, 29, 43,
       26, 34, 78, 40, 49, 41, 55, 78, 29, 70, 58, 64, 76, 68, 95, 88, 68,
       92, 62, 35, 54, 31, 56, 68])

In [174]:
sum(arr[arr > 25])

2381

In [175]:
arr[arr > 25].sum()

2381

In [176]:
arr[arr > 25].std()

21.76413501321129

In [177]:
arr[arr >25].min()

26

In [178]:
arr[arr > 25].max()

97

In [179]:
arr[arr > 25].var()

473.6775728732897

### arithmatic operations

In [180]:
a = np.array([4,5,6])
b = np.array([1,2,3])

In [181]:
a + b

array([5, 7, 9])

In [182]:
a - b

array([3, 3, 3])

In [183]:
a * b

array([ 4, 10, 18])

In [184]:
a / b

array([4. , 2.5, 2. ])

In [185]:
a ** b

array([  4,  25, 216])

In [186]:
a // b

array([4, 2, 2])

In [187]:
a % b

array([0, 1, 0])

In [188]:
np.add(a,b)

array([5, 7, 9])

In [190]:
np.subtract(a,b)

array([3, 3, 3])

In [191]:
np.multiply(a,b)

array([ 4, 10, 18])

In [192]:
np.divide(a,b)

array([4. , 2.5, 2. ])

In [193]:
np.power(a,b)

array([  4,  25, 216])

In [194]:
np.inf

inf

In [195]:
np.pi

3.141592653589793

### correlation

In [196]:
height = np.array([177, 192, 178, 158, 165, 168, 164, 161])
weight = np.array([85, 95, 74, 65, 60, 52, 52, 63])

In [197]:
np.corrcoef(height, weight)

array([[1.        , 0.83138299],
       [0.83138299, 1.        ]])